console.log('hello');
let A=0;
try{
    console.log(A);
}
catch(err)
{
    console.log(err);
}
finally
{
    console.log("this will exceute always");
}


console.log("joe");